# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 23, 8, 43, 23, 883585, tzinfo=utc)),
        ),
    ]
