# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import fourms.models


class Migration(migrations.Migration):

    dependencies = [
        ('fourms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=fourms.models.post_upload_location),
        ),
    ]
