# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 14:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fourms', '0002_auto_20170430_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fourms',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='fourms',
            name='subscriber',
            field=models.ManyToManyField(default=1, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
