# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20161012_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
