# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
