# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
        ('classroom', '0004_classroom_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='background.Background'),
        ),
    ]
