# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20161018_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
