# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourms', '0002_auto_20170430_1855'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fourms',
            field=models.ManyToManyField(related_name='studentforum', to='fourms.Fourms'),
        ),
    ]
