# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20161012_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
