# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20161012_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first',
            field=models.BooleanField(default=True),
        ),
    ]
