# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourms', '0001_initial'),
        ('student', '0016_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fourms',
            field=models.ManyToManyField(related_name='student_fourms', to='fourms.Fourms'),
        ),
    ]
