# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 15:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourms', '0004_auto_20170430_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourms',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
