# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-01 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('description', models.TextField(max_length=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='background.Background')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
