# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
