# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import teacher.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to=teacher.models.download_location)),
                ('name', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('address', models.TextField(max_length=300, null=True)),
                ('first', models.BooleanField(default=True)),
            ],
        ),
    ]
