# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
