# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-01 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20170401_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
