# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
