# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourms', '0001_initial'),
        ('teacher', '0006_auto_20170401_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='fourms',
            field=models.ManyToManyField(related_name='teacher_fourms', to='fourms.Fourms'),
        ),
    ]
