# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20161012_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
