# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20161012_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(choices=[(2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('', 'branch'), ('cse', 'CSE'), ('ece', 'ECE'), ('mae', 'MAE')], default=None, max_length=3, null=True),
        ),
    ]
