# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20161012_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
