# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 08:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20170412_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=datetime.date(2017, 4, 23)),
        ),
    ]
