# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20170423_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
