# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20161106_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
