# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161018_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'post'), ('anouncement', 'anouncement'), ('question', 'question'), ('assignment', 'assignment')], default='post', max_length=12),
        ),
    ]
