# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-12 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20161121_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Post',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.upload_location),
        ),
        migrations.DeleteModel(
            name='file',
        ),
    ]
