# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-23 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20170423_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'post'), ('anouncement', 'anouncement'), ('question', 'question')], default='post', max_length=12),
        ),
    ]
